### PR TITLE
add 'updated' method to Image

### PR DESCRIPTION
**Pull request by theolundqvist**
add method 'updated' to image for convenience.

### CODE REVIEW

**Comment by bjornregnell** [comment]
Sorry for not spotting this new PR. This will have to go in 1.2.1 but we release introprog with 1.2.0 as its already out on maven central...

**Comment by bjornregnell** [comment]
I'll merge this after course start and post physical print of course material. We can then make errata on homepage with this later. Plenty of time until project time in December...

**Comment by bjornregnell** [comment]
Please revert code to work in 1.2.0 in introprog teaching material and workspace.

**Comment by theolundqvist** [comment]
https://github.com/lunduniversity/introprog/pull/569

**Pull request merged**
