### PR TITLE
Add look and feel checks for WSL. fix #26

### LINKED ISSUE #26: Add detection of look and feel for WSL
Running the library on WSL currently throws an exception due to wrong look and feel being used (`javax.swing.UnsupportedLookAndFeelException`). GTK+ is incorrectly chosen, when it should be the same as for Windows. A check should be added to determine this for WSL.

See also PR #27

### PR DESCRIPTION
**Pull request by sadphi**
This hopefully fixes the issue on WSL where the incorrect look and feel is selected (GTK+), when it should be the same as on Windows.

### CODE REVIEW

**Comment by bjornregnell** [comment]
Thanks!! I think I'd prefer giving both the options "-q" and "-s" separately to shut up file not found and then also skip the macOs test inside isInProc. Feels more straight forward and simpler to read and understand. Could you fix that @sadphi

**Comment by bjornregnell** [comment]
Also we would need volunteers for each and every OS to test Linux/Windows/MacOS/WSL/WSL2 etc. The more the merrier. Reports here are welcome, if you want to try out the fork of @sadphi

**Comment by sadphi** [comment]
I've updated the code based on your comments. I've tested it on vanilla Windows and found no issues, and it also seems to be working now on WSL as well when using GWSL.

**Comment by sadphi** [comment]
> OK nice.
> But wasn't it InProg("Microsoft") as well a possible alternative to look for to detect WSL?
> https://github.com/microsoft/WSL/issues/4071#issuecomment-496737093

Hmm, if I recall correctly `/proc/version` only showed `windows` on the machine I tested. 

But based on that issue I guess it's just safer to include `microsoft` as well, because it seems to vary from system to system, even with similar setups.

I can add this tomorrow.

**Comment by sadphi** [comment]
I added `microsoft` as a search string in the latest commit, but I also rewrote `isInProc()` to instead take repeated parameters, so that grep can search for all of them at the same time using regexp.

**Comment by bjornregnell** [comment]
Cool! Could you also try to elicit some test reports that are given here by one or two people running some specified setup  (WSL1|WSL2 & GWSL version ? & Windows 10 | Windows 11 if possible).

**Comment by bjornregnell** [comment]
I'll merge this now and soon make a release here on github for more people toi test it before we make a release on maven central.

**Comment by sadphi** [comment]
Great! I'll report if I find any issues

**Comment by bjornregnell** [comment]
It just struck me that we should use java File instead -- it's kind of heavy to fire up a whole new OS process just to check what's in a file. I did not question the tip on how to detect WSL. So before we make an ordinary release to Maven central 1.3.1 we should fix this. And the isInProc is an implementation detail that should not be visible outside, and actually a part of isOS so that method should use a private isInProc. If so, the code would feel more "natural".

**Comment by bjornregnell** [comment]
New issue here now: https://github.com/lunduniversity/introprog-scalalib/issues/29

**Pull request merged**
